//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeldaSert.DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Evrak
    {
        public int Id { get; set; }
        [DisplayName("Ad")]
        public string evrakAd { get; set; }
        public Nullable<int> userId { get; set; }
        [DisplayName("Evrak Adresi")]
        public string evrakYol { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Tarih")]
        
        public Nullable<System.DateTime> evrakTarih { get; set; }
        [DisplayName("Durum")]
        public string evrakDurum { get; set; }
        [DisplayName("Aciklama")]
        public string Aciklama { get; set; }
    
        public virtual User User { get; set; }
    }
}
